DM-21997: Compare MultiProFit COSMOS fits in HSC-[IZ] vs HST-F814W
lsst-dm/modelling_research pull request #4
Opened 2020-01-13 21:34 UTC by taranu

2020-01-14 23:01 UTC, erykoff requested changes
This is all very interesting, and there's a lot to digest.  I do have some questions/comments that I hope are not too hard to address.
- Some sort of explanation for what is in the plots at the top would be helpful.  Eg, what are the blue points? What are the black points? What is the shading algorithm?
- It would also be nice to have a comment on what you think the lesson is from each of these plots.
- Many of the plots have big peaks in the percentiles, notably the first one, that don't seem to quite make sense with the shaded region.  It might be that I don't understand what the shaded region represents.
- When you have a histogram on the right side, it would be useful to have an estimate of the mean and width of the distribution (in some robust way to not get caught up with the far outlier peaks)
- What's the story with the very small r_eff for the dev fits relative to mmf?  I think we discussed this a bit in Princeton, and I don't recall the conclusion.
- Why is there such a large offset between mg8serb and cmodel at the bright end?
- I was expecting to see some magnitude comparisons between HSC and HST but there were just sizes.

2020-01-17 20:22 UTC, taranu commented
>    *  Some sort of explanation for what is in the plots at the top would be helpful. Eg, what are the blue points? What are the black points? What is the shading algorithm?
>    *    It would also be nice to have a comment on what you think the lesson is from each of these plots.

I'll add more explanatory text.

>     * Many of the plots have big peaks in the percentiles, notably the first one, that don't seem to quite make sense with the shaded region.  It might be that I don't understand what the shaded region represents.

The shading is a 2D KDE with some default kernel that I didn't change and is therefore more sensitive to the distribution on the x-axis than the running percentiles, which are usually more local. e.g. imagine if the density along the x-axis varied sinusoidally but the y-axis scatter was Gaussian with constant sigma - the KDE density would look like beads on a string whereas the running percentiles would all be flat. Here's an example:

![image](https://user-images.githubusercontent.com/10129954/72641958-4f9f9900-3939-11ea-9e36-2131be07f20c.png)
 
>     * When you have a histogram on the right side, it would be useful to have an estimate of the mean and width of the distribution (in some robust way to not get caught up with the far outlier peaks)

In almost every plot the percentiles vary over the x-range, so I think I'd rather force viewers to read them at their preferred x-axis value for now.

>     * What's the story with the very small r_eff for the dev fits relative to mmf?  I think we discussed this a bit in Princeton, and I don't recall the conclusion.

This was partly because mpf's lower limit is 0.01 pix where mmf is 0.1 pix. Having changed the plot limits, the difference remains for r_eff > 1 pix. I suspect it's the difference in the dev approximations, especially at the bright end. mmf uses Tractor's luv profile which might truncate more quickly than mpf (I'd have to verify this), leading to larger r_eff. mmf also has a size prior and especially for dev a lot of galaxies seem to pile up there; chances are most of them are smaller than that size (seems to be around 4 pixels).
 
>     * Why is there such a large offset between mg8serb and cmodel at the bright end?

The median ~0.03 mag difference? I'm not worried about that. The asymmetric distribution is probably because of how the models map on to each other: n=1 and n=4 can be exactly represented by cmodel; 1<n<4 will do whatever they do, and n<1 and n>4 can't be represented by cmodel and are probably mostly better fit by a Sersic profile with some non-zero bias.

>     * I was expecting to see some magnitude comparisons between HSC and HST but there were just sizes.

I put them in but they are, uh, not great. I am not an expert on photometric calibration...

2020-01-30 22:42 UTC, erykoff approved these changes

2020-01-30 22:44 UTC, erykoff commented
I see that the full changes are on DM-22161, which will be coming soon.

2020-01-31 16:22 UTC, merged